import { TILES } from '../consts';

const { END, BUSH, FLOWER, GRASS, MUD, ROCK, START, TREE } = TILES;

export default [
  [GRASS, TREE, GRASS, GRASS, ROCK, FLOWER, TREE],
  [TREE, FLOWER, GRASS, MUD, MUD, MUD, ROCK],
  [START, MUD, MUD, MUD, ROCK, MUD, ROCK],
  [GRASS, FLOWER, GRASS, MUD, ROCK, END, TREE],
  [GRASS, GRASS, GRASS, GRASS, ROCK, GRASS, TREE],
];
